version: "3.5"

services:
    keycloak:
        image: mocap/keycloak
        container_name: mocap-keycloak
        build:
            context: ./
            dockerfile: Dockerfile
            target: ${TARGET:-local}
        env_file:
            - .env.production
            - .env.production.local
        networks:
            - mocap
        ports:
            - 8888:8080 # web ui
        restart: always
        command: start --import-realm --hostname-url=$${KEYCLOAK_HOSTNAME}$${KEYCLOAK_HOST_PATH} --http-relative-path=$${KEYCLOAK_HOST_PATH} --proxy edge --db postgres --db-url=$${DATABASE_URL} --db-username=$${DATABASE_USERNAME} --db-password=$${DATABASE_PASSWORD}
networks:
    mocap:
        external: true
