name: build-docker-image

on:
    push:
        paths-ignore:
            - README.md
        branches:
            - master
    pull_request:
        paths-ignore:
            - README.md

jobs:
    build-docker-image:
        name: Build Image
        runs-on: ubuntu-20.04
        steps:
            - uses: docker/build-push-action@v5
              with:
                  push: false
                  tags: mocap/keycloak:latest
